name: CI/CD CRUD Kesehatan

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy ke EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@16.176.207.27 << EOF
        echo "=== MASUK SERVER ==="
        cd /var/www/simpleHealth
        git fetch --all
        git reset --hard origin/main
        npm install
        pm2 restart all
        sudo systemctl restart nginx
        echo "=== SELESAI ==="
        EOF